name: AntiChests
version: '1.1'
main: me.itzstanleex.antichests.AntiChests
api-version: '1.21'
author: ItzStanleex
commands:
  antichest:
    description: Deletes all items from containers within a certain radius
    usage: /antichest <radius>
    permission: antichest.use

permissions:
  antichest.use:
    description: Allows use of the /antichest command
    default: op
