name: AntiChests
version: '1.1'
main: me.itzstanleex.antichests.AntiChests
api-version: '1.21'
author: ItzStanleex
commands:
  antichest:
    description: Smaže všechny věci z containerů v určitém radiusu
    usage: /antichest <radius>
    permission: antichest.use

permissions:
  antichest.use:
    description: Umožňuje použití příkazu /antichest
    default: op